name: deploy main branch

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github
          gpg-private-key: ${{ secrets.ARTIFACT_SIGNING_GPG_PRIVATE_KEY }}
          server-username: SERVER_USER
          server-password: ${{ secrets.DEPLOY_TOKEN_GITHUB_PACKAGES }}
      - name: execute maven
        run: export GPG_TTY=$(tty) && mvn --batch-mode -e deploy
        env:
          GPG_KEY_NAME: ${{ secrets.ARTIFACT_SIGNING_GPG_KEY_NAME }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.ARTIFACT_SIGNING_GPG_PRIVATE_KEY_PASSWORD }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVER_USER: ${{ secrets.DEPLOY_USER_GITHUB_PACKAGES }}
#          SERVER_PASSWORD: ${{ secrets.DEPLOY_TOKEN_GITHUB_PACKAGES }}